### ISSUE TITLE
Loops only twice

### ISSUE THREAD

**Issue by OperationDarkside** [mattdear/matts_dice_game#16]
In the file Game.java in line 57 I imagine you want to loop 3 times, but the loop header will only do it twice.

```C++
for (int i = 1; i < 3; i++) {
     System.out.println(i);
}
```

**Comment by mattdear** [comment]
Thank you for this.

You should only be able to hold dice on the second and third roll attempts this is the reason this only runs twice because you cannot hold dice you have not rolled.

**Comment by OperationDarkside** [comment]
But with this code line 61 will never show "Roll 3 of 3". This might be intended, but would confuse me as a player
